# development profile
eureka:
  instance:
    hostname: localhost12345678
  server:
    enable-self-preservation: false
    
spring:
  security:
    user:
      name: eurekaLocalUser
      password: eurekaLocalPassword